#!/bin/bash

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/global_var
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/verify_root
. /etc/server_admin/menu/networks/common

enable_firewall() {
	firewall-cmd -q --permanent --add-port=21/tcp
	firewall-cmd -q --reload
}

install_vsftpd() {
	if [ -f /lib/systemd/system/vsftpd.service ]; then
	  	yum update -y -q vsftpd
	else
		yum install -y -q vsftpd
	fi
}

create_user() {
	if ! id -u ftpuser > /dev/null 2>&1; then
	   	#Add ftp user
		useradd ftpuser
		passwd ftpuser
	fi
    #Add ftpuser to ftp group
	usermod -a -G ftp ftpuser
}



yum update -y -q &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Updating system...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"


create_user &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Creating fpt user...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

install_vsftpd &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Installing vsftpd...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

enable_firewall &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Enabling firewall for vsftpd...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

systemctl stop vsftpd

get_user_name() {
	echo -n "Enter ftp account's username then press [ENTER]: "
	while read username
	do
	if [ "$username" != "" ]; then
	    break
	fi
	echo -n "Username should not be blank, enter your username: "
	done
}

get_password() {
	echo -n "Enter ftp account's password then press [ENTER]: "
	while read -s password
	do
	if [ "$password" != "" ]; then
	    break
	fi
	echo -n "Password should not be blank, enter your password: "
	done
}

finish() {
	systemctl enable vsftpd -q
	if [ $? -eq 1 ]; then
		echo -e -n "${BRed}Enable vsftpd error${Color_Off} "
        return 1
    fi
	if [ $? -eq 1 ]; then
		echo -e -n "${BRed}Start vsftpd error${Color_Off} "
        return 1
    fi
	setsebool -P ftpd_full_access on
	if [ $? -eq 1 ]; then
		echo -e -n "${BRed}Enable ftpd_full_access error${Color_Off} "
        return 1
    fi

    if [ ! -d /home/ftpuser/vftp ]; then
	  mkdir /home/ftpuser/vftp
	fi
	chown -R ftpuser:ftp /home/ftpuser/vftp/
	chmod 755 -R /home/ftpuser/vftp
	#Restart vsftpd
	systemctl restart vsftpd
	return 0
}

cat > "/etc/pam.d/vsftpd.virtual" <<END
#%PAM-1.0
auth required pam_userdb.so db=/etc/vsftpd/vsftpd-virtual-user
account required pam_userdb.so db=/etc/vsftpd/vsftpd-virtual-user
session required pam_loginuid.so
END
#Backup vsftpd.conf
cp /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.origin
echo '' > /etc/vsftpd/vsftpd.conf
cat > "/etc/vsftpd/vsftpd.conf" <<END
listen=YES
#Disallow anonymous logins; this allows unidentified users to access files via FTP. Ensure that the anonymous_enable setting to NO:
anonymous_enable=NO
#Enable local users to login, this will allow your regular user accounts to function as FTP accounts. Change the local_enable setting to YES:
local_enable=YES
#If you want local user to be able to write to a directory, then change the write_enable setting to YES:
write_enable=YES
local_umask=022
nopriv_user=ftpuser
virtual_use_local_privs=YES
guest_enable=YES
#local_root=/home/ftpuser/vftp
#Local users will be ‘chroot jailed’ and they will be denied access to any other part of the server. Set the chroot_local_user setting to YES:
chroot_local_user=YES
allow_writeable_chroot=YES
ls_recurse_enable=YES
pam_service_name=vsftpd.virtual
## Home Directory for virtual users
user_sub_token=\$USER
local_root=/home/ftpuser/vftp/\$USER
max_clients=5
hide_ids=YES
chroot_list_enable=NO
userlist_deny=YES
userlist_file=/etc/vsftpd/user_list
guest_enable=YES
guest_username=ftpuser
user_config_dir=/etc/vsftpd/vsftpd_user_conf
END


printf "\n"
finish &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Configuring vsftpd...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

if [ $? -eq 0 ]; then
    clear
	echo "===================================================================================="
	echo -e "         INSTALL VSFTPD SUCCESSFUL"
	echo "===================================================================================="
	read -p "Do you want to create ftp account?  " -n 1 -r
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		printf "\n"
		/etc/server_admin/menu/networks/create_ftp_user
	else
		back_to_menu
	fi
else
	back_to_menu
fi