#!/bin/bash

clear

. /etc/server_admin/menu/color.sh

install_nodejs() {
	tar -xzf /home/root/node-v* > /dev/null 2>&1 && cd /home/root/node-v*
	if [ $? -eq 0 ]; then
		sudo yum install gcc gcc-c++ -y -q
		if [ $? -eq 0 ]; then
			./configure
			if [ $? -eq 0 ]; then
				make
				if [ $? -eq 0 ]; then
					sudo make install
					if [ $? -eq 0 ]; then
						return 0
					else
						return 1
					fi
				else
					return 1
				fi
			else
				return 1
			fi
		else
			return 1
		fi
	else
		return 1
	fi
}

echo -e "You should go to\n"
echo -e "${BBlue}https://nodejs.org/download/release/latest/${Color_Off}\n"
echo -e "To get latest version of nodejs (.tar.gz file) \n"

echo -n -e "Paste url of nodejs latest build:: "
read nodejs_url

wget -q -P /home/root $nodejs_url &
PID=$!
i=1
sp="/-\|"
echo -e -n "${BGreen}Downloading nodejs...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

rm -rf /home/root/node-v*

install_nodejs &
PID=$!
i=1
sp="/-\|"
echo -e -n "${BGreen}Installing nodejs...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"
if [ $? -eq 0 ]; then
	clear
	echo "===================================================================================="
	echo -e "         ${BGreen}INSTALL NODEJS SUCCESSFUL${Color_Off}"
	echo "===================================================================================="
	read -p "Press enter to continue"
	server-admin
	exit;
else
	read -p "Press enter to continue"
	server-admin
	exit
fi