#!/bin/bash

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

yum update -y -q &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Updating system...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
printf "\n"

#Add ftp user
useradd ftpuser
passwd ftpuser

#Add ftpuser to ftp group
usermod -a -G ftp ftpuser

yum install -y -q vsftpd &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Installing vsftpd...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
printf "\n"

systemctl stop vsftpd

get_user_name() {
	echo -n "Enter your username then press [ENTER]: "
	while read username
	do
	if [ "$username" != "" ]; then
	    break
	fi
	echo -n "Username should not be blank, enter your username: "
	done
}

get_password() {
	echo -n "Enter your password then press [ENTER]: "
	while read -s password
	do
	if [ "$password" != "" ]; then
	    break
	fi
	echo -n "Password should not be blank, enter your password: "
	done
}

finish() {
	systemctl enable vsftpd
	if [ $? -eq 1 ]; then
        return 1
    fi
	#Restart vsftpd
	systemctl restart vsftpd
	if [ $? -eq 1 ]; then
        return 1
    fi
	setsebool -P ftpd_full_access on
	if [ $? -eq 1 ]; then
        return 1
    fi
	mkdir /home/ftpuser/vftp
	if [ $? -eq 1 ]; then
        return 1
    fi
	chown -R ftpuser /home/ftpuser/vftp/
	chmod 755 -R /home/ftpuser/vftp
	return 0
}

get_user_name
get_password

cat > "/etc/vsftpd/user.txt" <<END
$username 
$password
END
db_load -T -t hash -f /etc/vsftpd/user.txt /etc/vsftpd/vsftpd-virtual-user.db
chmod 600 /etc/vsftpd/vsftpd-virtual-user.db
cat > "/etc/pam.d/vsftpd.virtual" <<END
#%PAM-1.0
auth required pam_userdb.so db=/etc/vsftpd/vsftpd-virtual-user
account required pam_userdb.so db=/etc/vsftpd/vsftpd-virtual-user
session required pam_loginuid.so
END
#Backup vsftpd.conf
cp /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.origin
echo '' > /etc/vsftpd/vsftpd.conf
cat > "/etc/vsftpd/vsftpd.conf" <<END
listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
nopriv_user=ftpuser
virtual_use_local_privs=YES
guest_enable=YES
local_root=/home/ftpuser/vftp
chroot_local_user=NO
allow_writeable_chroot=YES
ls_recurse_enable=YES
pam_service_name=vsftpd.virtual
max_clients=5
hide_ids=YES
chroot_list_enable=NO
userlist_deny=YES
userlist_file=/etc/vsftpd/user_list
guest_enable=YES
guest_username=ftpuser
user_config_dir=/etc/vsftpd/vsftpd_user_conf
END



finish &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Configuring vsftpd...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
printf "\n"

if [ $? -eq 1 ]; then
    clear
	echo "===================================================================================="
	echo -e "         ${BGreen} USER: $username${Color_Off}"
	echo -e "         ${BBlue} PASSWORD: $password${Color_Off}"
	echo "===================================================================================="
	read -p "Press enter to continue"
	server-admin
	exit;
else
	read -p "Error. Press enter to continue"
	server-admin
	exit;
fi