#!/bin/sh

yum update -y
# Install epel
yum install epel-release yum-utils -y
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
# Install nginx
yum install nginx -y

firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload

current_time=`date '+%Y-%m-%d_%H_%M_%S'`
server_ip=`hostname -I`

yum install -y unzip wget
cd ~
wget -q https://github.com/iphuongtt/server-configs-nginx/archive/master.zip
unzip -q master.zip && rm -f master.zip
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup$current_time
cp server-configs-nginx-master/nginx.conf /etc/nginx/nginx.conf
cp server-configs-nginx-master/mime.types /etc/nginx/mime.types
cp -R server-configs-nginx-master/sites-available /etc/nginx/
cp -R server-configs-nginx-master/sites-enabled /etc/nginx/
cp -R server-configs-nginx-master/h5bp /etc/nginx/
# Delete server-configs-nginx-master
rm -rf ~/server-configs-nginx-master
# Auto start nginx when server stared
systemctl enable nginx
systemctl start nginx