#!/bin/bash
yum update -y

cat > "/etc/yum.repos.d/MariaDB.repo" <<END
[mariadb]

name = MariaDB

baseurl = http://yum.mariadb.org/10.1/centos7-amd64

gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

gpgcheck=1
END
yum --enablerepo=remi install mariadb-server mariadb -y
systemctl enable mariadb.service
systemctl start mariadb.service
mysql_secure_installation