#!/bin/sh

printf "=========================================================================\n"
printf "                             LIST VIRTUALHOST\n"
printf "=========================================================================\n"
grep -RiI server_name /etc/nginx/sites-enabled/ 
read -p "Press enter to continue"
server-admin