#!/bin/bash

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/global_var

echo -n "Enter ftp account's username: "
read username

echo -n "Enter folder path to mount: "
read path

pathConvert=`echo $path | sed -r "s/\~/\/home\/$logon_username/"`

check_folder_exits $pathConvert
folderName=`basename $pathConvert`

mkdir /home/ftpuser/vftp/$username/$folderName

mount --bind $folderConvert /home/ftpuser/vftp/$username/$folderName 

sed -i -e "$ a $folderConvert /home/ftpuser/vftp/$username/$folderName none bind 0 0" /etc/fstab