#!/bin/bash

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/global_var


input_username() {
	echo -n "Enter ftp account's username: "
	while read username
	do
		if [ "$username" != "" ]; then
		    break
		fi
		echo -n "Username should not be blank, enter your username: "
	done
	if ! is_folder_exists /home/ftpuser/vftp/$username; then
		read -p "Account: $username does not exists. Do you want to try again?:  " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			printf "\n"
			input_username
		else
			server_admin
			exit
		fi
	fi
}


input_folder() {
	echo -n "Enter folder path to mount: "
	while read path
	do
		if [ "$path" != "" ]; then
		    break
		fi
		echo -n "Path should not be blank, enter your path: "
	done
	pathConvert=`echo $path | sed -r "s/\~/\/home\/$logon_username/"`
	if ! is_folder_exists $pathConvert; then
		read -p "$pathConvert does not exists. Do you want to try again?:  " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			printf "\n"
			input_folder
		else
			server_admin
			exit
		fi
	fi 
}

input_username

input_folder
 
folderName=`basename $pathConvert`

mkdir /home/ftpuser/vftp/$username/$folderName

mount --bind $pathConvert /home/ftpuser/vftp/$username/$folderName 

sed -i -e "$ a $pathConvert /home/ftpuser/vftp/$username/$folderName none bind 0 0" /etc/fstab

if [ $? -eq 1 ]; then
	clear
	echo "===================================================================================="
	echo -e "         ${BGreen} Mounted: $pathConvert to /home/ftpuser/vftp/$username/$folderName {Color_Off}"
	echo "===================================================================================="
	read -p "Press enter to continue"
	server-admin
	exit;
else
	read -p "Error, Press enter to continue"
	server-admin
	exit;
fi