#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/global_var

yum remove -y -q php* &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Removing all php version...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"


if [ $? -eq 0 ]; then
	clear
	echo "===================================================================================="
	echo -e "         ${BGreen}REMOVED ALL PHP VERSION SUCCESSFUL${Color_Off}"
	echo "===================================================================================="
	read -p "Press enter to continue"
	server-admin
	exit;
else
	read -p "Press enter to continue"
	server-admin
	exit;
fi
