#!/bin/bash

cd ~

git clone https://github.com/iphuongtt/server_admin_script.git server_admin_script

cd server_admin_script/centos7

bash install.sh

rm -rf ~/server_admin_script

read -p "Press enter to continue"

server-admin