#!/bin/bash

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/global_var

git clone -q https://github.com/iphuongtt/server_admin_script.git /var/server_admin_script &
PID=$!
i=1
sp="/-\|"
echo -e -n "${BGreen}Downloading source code...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
printf "\n"
if [ $? -eq 1 ]; then
	echo -e "${BRed}Please check your internet connection...${Color_Off}"
	read -p "Press enter to continue"
	server-admin
	exit
fi
echo -e "${BGreen}Installing server-admin tool...${Color_Off}"
bash /var/server_admin_script/centos7/install.sh
if [ $? -eq 1 ]; then
	echo -e "${BGreen}Deleting folder code...${Color_Off}"
	rm -rf /var/server_admin_script
	echo -e "${BRed}Please contact to developer to developer...${Color_Off}"
	read -p "Press enter to continue"
	server-admin
	exit
else
	echo -e "${BGreen}Deleting folder source code...${Color_Off}"
	rm -rf /var/server_admin_script
	echo -e "${ICyan}Update successful!${Color_Off}"
	read -p "Press enter to continue"
	server-admin
	exit
fi