#!/bin/bash

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/global_var


input_username() {
	echo -n "Enter ftp account's username: "
	while read username
	do
		if [ "$username" != "" ]; then
		    break
		fi
		echo -n "Username should not be blank, enter your username: "
	done
	if ! is_folder_exists /home/ftpuser/vftp/$username; then
		read -p "Account: $username does not exists. Do you want to try again?:  " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			printf "\n"
			input_username
		else
			server-admin
			exit
		fi
	fi
}


input_folder() {
	echo -n "Enter folder name to unmount: "
	while read folderName
	do
		if [ "$folderName" != "" ]; then
		    break
		fi
		echo -n "Folder name should not be blank, enter your folder name: "
	done
	if ! is_folder_exists /home/ftpuser/vftp/$username/$folderName; then
		read -p "/home/ftpuser/vftp/$username/$folderName does not exists. Do you want to try again?:  " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			printf "\n"
			input_folder
		else
			server-admin
			exit
		fi
	fi 
}

input_username

input_folder

umount /home/ftpuser/vftp/$username/$folderName 

sed -i -e "/home/ftpuser/vftp/$username/$folderName none bind 0 0/d" /etc/fstab

if [ $? -eq 1 ]; then
	clear
	echo "===================================================================================="
	echo -e "         ${BGreen} Unmounted: /home/ftpuser/vftp/$username/$folderName${Color_Off}"
	echo "===================================================================================="
	read -p "Press enter to continue"
	server-admin
	exit;
else
	read -p "Error, Press enter to continue"
	server-admin
	exit;
fi