#!/bin/bash

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/global_var
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/verify_root
. /etc/server_admin/menu/networks/common

config_firewall() {
	firewall-cmd --permanent --zone=public --add-service=http
	firewall-cmd --permanent --zone=public --add-service=https
	firewall-cmd --reload
}

update_system

# Install nginx
yum install nginx -y -q &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Installing Nginx...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

config_firewall &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Configuring firewall...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

cd ~
wget -q https://github.com/iphuongtt/server-configs-nginx/archive/master.zip
unzip -q master.zip && rm -f master.zip
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup$current_time
cp server-configs-nginx-master/nginx.conf /etc/nginx/nginx.conf
cp server-configs-nginx-master/mime.types /etc/nginx/mime.types
cp -R server-configs-nginx-master/sites-available /etc/nginx/
cp -R server-configs-nginx-master/sites-enabled /etc/nginx/
cp -R server-configs-nginx-master/h5bp /etc/nginx/
mkdir /etc/nginx/ssl
# Delete server-configs-nginx-master
rm -rf ~/server-configs-nginx-master
# Auto start nginx when server stared
systemctl enable nginx
systemctl start nginx

echo "========================================================="
echo -e "||||     \e[0;34m INSTALL NGINX SUCCESSFUL \e[0m     ||||"
echo "========================================================="
sleep 5

back_to_menu