#!/bin/bash

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/verify_root

is_folder_exists() {
	if [ -d $1 ]; then
	   	return 0;
	else
		return 1;
	fi
}

update_system() {
	yum update -y -q &
	PID=$!
	i=1
	sp="/-\|"
	echo -e -n "${BGreen}Updating system...${Color_Off} "
	while [ -d /proc/$PID ]
	do
	  printf "\b${sp:i++%${#sp}:1}"
	done
	echo -e "${BBlue} Done${Color_Off}"
	printf "\n"
}

install_common_package() {
	yum install wget epel-release yum-utils http://rpms.remirepo.net/enterprise/remi-release-7.rpm unzip -y -q   > /dev/null 2>&1 &
	PID=$!
	i=1
	sp="/-\|"
	echo -e -n "${BGreen}Installing common packages...${Color_Off} "
	while [ -d /proc/$PID ]
	do
	  printf "\b${sp:i++%${#sp}:1}"
	done
	echo -e "${BBlue} Done${Color_Off}"
	printf "\n"
}
if ! is_folder_exists /var/server_admin_script; then
	rm -rf /var/server_admin_script
fi

git clone -q https://github.com/iphuongtt/server_admin_script.git /var/server_admin_script &
PID=$!
i=1
sp="/-\|"
echo -e -n "${BGreen}Downloading source code...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"
if [ $? -eq 1 ]; then
	echo -e "${BRed}Please check your internet connection...${Color_Off}"
	read -p "Press enter to continue"
	server-admin
	exit
fi
echo -e "${BGreen}Installing server-admin tool...${Color_Off}"

. /var/server_admin_script/centos8/menu/global_var

mkdir -p /etc/server_admin/menu/
mkdir -p /etc/server_admin/templates/
cp /var/server_admin_script/centos8/server_admin.sh /bin/server-admin && chmod +x /bin/server-admin
cp -R /var/server_admin_script/centos8/menu/* /etc/server_admin/menu/
cp -R /var/server_admin_script/templates/* /etc/server_admin/templates/
chmod -R +x /etc/server_admin/menu/*

if [ $? -eq 1 ]; then
	echo -e "${BGreen}Deleting folder code...${Color_Off}"
	rm -rf /var/server_admin_script
	echo -e "${BRed}Please contact to developer to developer...${Color_Off}"
	read -p "Press enter to continue"
	server-admin
	exit;
else
	echo -e "${BGreen}Deleting folder source code...${Color_Off}"
	rm -rf /var/server_admin_script
	echo -e "${ICyan}Update successful!${Color_Off}"
	update_system
	install_common_package
	read -p "Press enter to continue"
	server-admin
	exit;
fi
