#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/global_var
. /etc/server_admin/menu/verify_root
. /etc/server_admin/menu/developments/common

config_firewall() {
	firewall-cmd --permanent --zone=public --add-service=http -q
	firewall-cmd --permanent --zone=public --add-service=https -q
	firewall-cmd --reload -q
}

install_php() {
	yum-config-manager --enable remi-php$php_install -q
	yum --enablerepo=remi,remi-php$php_install install php-fpm php-common -y -q
	yum --enablerepo=remi,remi-php$php_install install php-opcache php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-pecl-mongodb php-pecl-redis php-pecl-memcache php-pecl-memcached php-gd php-mbstring php-mcrypt php-xml php-pecl-zip php-odbc -y -q
}
config_php() {
	cp /etc/php.ini /etc/php.ini.backup$current_time
	sed -i 's/cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php.ini # This causes the PHP interpreter to only try the literal path given and to stop processing if the file is not found.

	# Config php-fpm
	cp /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.backup$current_time
	sed -i 's/user = apache/user = nginx/' /etc/php-fpm.d/www.conf
	sed -i 's/group = apache/group = nginx/' /etc/php-fpm.d/www.conf
	sed -i 's/listen.owner = nobody/listen.owner = nginx/' /etc/php-fpm.d/www.conf
	sed -i 's/listen.group = nobody/listen.group = nginx/' /etc/php-fpm.d/www.conf
	sed -i 's/listen = 127.0.0.1:9000/listen = /var/run/php-fpm/php-fpm.sock/' /etc/php-fpm.d/www.conf
}
clear
printf "=========================================================================\n"
printf "Begin installation... \n"
printf "=========================================================================\n"

printf "Chose PHP version:\n"
prompt="Enter your number [1-5]: "
php_version="7.1"; # Default PHP 7.1
php_install="71"
options=("PHP 7.0" "PHP 7.1" "PHP 7.2" "PHP 7.3")
PS3="$prompt"
select opt in "${options[@]}"; do 
    case "$REPLY" in
    1) php_version="7.0"; php_install="70"; break;;
    2) php_version="7.1"; php_install="71"; break;;
    3) php_version="7.2"; php_install="72"; break;;
    4) php_version="7.3"; php_install="73"; break;;
    # End Menu
    $(( ${#options[@]}+1 )) ) server-admin; break;;
    *) echo "Please, chose again";continue;;
    esac
done

update_system

config_firewall &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Configuring firewall...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

install_php &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Install Php $php_version...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

# Config Php
config_php &
PID=$!
i=1
sp="/-\|"
#echo -n ' '
echo -e -n "${BGreen}Configuring Php...${Color_Off} "
while [ -d /proc/$PID ]
do
  printf "\b${sp:i++%${#sp}:1}"
done
echo -e "${BBlue} Done${Color_Off}"
printf "\n"

systemctl enable php-fpm -q
if [ $? -eq 0 ]; then
	systemctl start php-fpm -q
	if [ $? -eq 0 ]; then
		clear
		echo "===================================================================================="
		echo -e "         ${BGreen}INSTALL PHP $php_version SUCCESSFUL${Color_Off}"
		echo "===================================================================================="
		back_to_menu
	else
		back_to_menu
	fi
else
	back_to_menu
fi

