#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/global.sh
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/verify_root
. /etc/server_admin/menu/developments/common

download_composer() {
	php -q -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &
	PID=$!
	i=1
	sp="/-\|"
	#echo -n ' '
	echo -e -n "${BGreen}Downloading composer...${Color_Off} "
	while [ -d /proc/$PID ]
	do
	  printf "\b${sp:i++%${#sp}:1}"
	done
	if [ $? -eq 0 ]; then
		echo -e "${BBlue} Done${Color_Off}"
		printf "\n"
		install_composer
	else
		back_to_menu
    fi
}

install_composer() {
	php composer-setup.php --install-dir=/usr/local/bin --filename=composer	 &
	PID=$!
	i=1
	sp="/-\|"
	#echo -n ' '
	echo -e -n "${BGreen}Installing composer...${Color_Off} "
	while [ -d /proc/$PID ]
	do
	  printf "\b${sp:i++%${#sp}:1}"
	done
	if [ $? -eq 0 ]; then
		clear;
		composer
		back_to_menu
	else
		back_to_menu
    fi
}

if [ ! -f /usr/local/bin/composer ]; then
	if [ ! -f /lib/systemd/system/php-fpm.service ]; then
	  read -p "PHP is required but is not installed. Do you want to install PHP?:  " -n 1 -r
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			/etc/server_admin/menu/install_php
			exit
		else
			echo "Can not install Composer"
			back_to_menu
		fi
	else
		download_composer
	fi
else
	echo -e -n "${BGreen}Composer has been installed...${Color_Off} ";
	printf "\n";
	echo -e -n "${BGreen}Updating composer...${Color_Off} ";
	printf "\n";
	composer self-update
	back_to_menu
fi