#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh

return_menu() {
	/etc/server_admin/menu/developments/menu
	exit
}

read_options(){
	case $1 in
		1) /etc/server_admin/menu/developments/install_nodejs; exit ;;
		2) /etc/server_admin/menu/developments/install_php; exit ;;
		3) /etc/server_admin/menu/developments/remove_all_php; exit ;;
		4) /etc/server_admin/menu/developments/install_mariadb; exit ;;
		5) /etc/server_admin/menu/developments/install_composer; exit ;;
		6) /etc/server_admin/menu/developments/create_mysql_database; exit ;;
		7) /etc/server_admin/menu/developments/create_user_mysql; exit ;;
		8) /etc/server_admin/menu/developments/backup_mysql_databases; exit ;;
		9) /etc/server_admin/menu/developments/uninstall_nodejs; exit ;;
		10) server-admin; exit ;;
		11) exit 0;;
		*) echo -e "${RED}Error...${Color_Off}"
	esac
}

trap 'return_menu' SIGINT SIGQUIT SIGTSTP

options=("INSTALL NODEJS" "INSTALL PHP" "REMOVE PHP VERSION" "INSTALL MARIADB 10.1" "INSTALL COMPOSER" "CREATE MYSQL DATABASE" "CREATE MYSQL USER" "BACKUP MYSQL DATABASES" "UNINSTALL NODEJS" "BACK TO ROOT MENU" "EXIT")
show_menu "D E V E L O P M E N T - T O O L S" "${options[@]}"
choice=$?
read_options $choice