#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh

return_menu() {
	/etc/server_admin/menu/utilities/menu
	exit
}

read_options(){
	case $1 in
		1) server-admin;;
		2) exit 0;;
	esac
}

trap 'return_menu' SIGINT SIGQUIT SIGTSTP
options=("BACK TO ROOT MENU" "EXIT")
show_menu "U T I L I T I E S - T O O L S" "${options[@]}"
choice=$?
read_options $choice