#!/bin/sh

clear
. /etc/server_admin/menu/color.sh

return_menu() {
	/etc/server_admin/menu/networks/menu
	exit
}

show_menus() {
	clear
	echo -e "${BGreen}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${Color_Off}"	
	echo -e "${BYellow} S Y S T E M - T O O L S ${Color_Off}"
	echo -e "${BGreen}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${Color_Off}"	
	echo -e "${BPurple}1.  BACK TO ROOT MENU${Color_Off}"
	echo -e "${BRed}2.  EXIT${Color_Off}"
}

read_options(){
	local choice
	read -p "Enter choice [ 1 - 2] " choice
	case $choice in
		1) server-admin; break ;;
		2) exit 0;;
		*) echo -e "${RED}Error...${Color_Off}"
	esac
}

trap 'return_menu' SIGINT SIGQUIT SIGTSTP

while true
do
	show_menus
	read_options
done