#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/global_var
. /etc/server_admin/menu/function.sh
. /etc/server_admin/menu/verify_root
. /etc/server_admin/menu/systems/common

echo -e "${BGreen}Current timezone:${Color_Off} \n"

timedatectl

read -p "Press enter to continue"

timedatectl list-timezones

echo -e "Input timezone to set:"
read timezone

timedatectl set-timezone $timezone && timedatectl

back_to_menu