#!/bin/sh

clear

. /etc/server_admin/menu/color.sh
. /etc/server_admin/menu/function.sh

return_menu() {
	/etc/server_admin/menu/developments/menu
	exit
}

read_options() {
	case $1 in
		1) /etc/server_admin/menu/developments/install_php;;
		2) /etc/server_admin/menu/developments/setup_to_connect_mssql;;
		3) server-admin;;
		4) clear; exit 0;;
	esac
}

trap 'return_menu' SIGINT SIGQUIT SIGTSTP

options=("INSTALL PHP" "SETUP TO CONNECT MSSQL" "BACK TO ROOT MENU" "EXIT")
show_menu "D E V E L O P M E N T - T O O L S" "${options[@]}"
choice=$?
read_options $choice
